### ISSUE TITLE
Re-style

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/visibleconsole.js#4]
Completely restyle the console with cross-browser css and make it awesome and organized in the example.

**Comment by ememmons** [comment]
![visibleconsole](https://f.cloud.github.com/assets/945307/59303/6311e2c2-5bb5-11e2-94f2-1ea3d5d376ef.png)
- Tweaked padding for console output area.
- Added text formatting and gradient background to header with solid color fallback.
- Added title to header: ~VisibleConsole~
- Added HR after each console log

##### Note:

Cross browser testing has not been competed. Will open a separate issue for that as resize functionality doesn't work in FireFox v18.0.
